export const majorGods= [
  {name: `Fauscht`, title: `Dieu de la mort, Père de la magie de la magie Grise`, img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Il est le dieu de la mort, reconnaissable par sa grande faux et son corbeau Ankou, on reconnaît son arrivée grâce au grincement de sa charrette. Il transporte à son bord les âmes des défunts qu’il mène soit au porte des enfers, soit aux abords de son bateau le “bag noz” pour faire passer des épreuves afin de savoir s’ils sont dignes d'entrer dans le palais des cieux. Ces épreuves sont diverses et dépendent de la personne, par exemple il y a de forte chance que pour un nains des montagnes ils lui fasse passer l’épreuves des 120 auberges ou  le nains doit boire tout ce qu’on lui sert sans s’arrêter. Contrairement à ce que son titre peut laisser penser, il est là pour accompagner dans la mort et sa venu, non pour tuer. De fait il n’est pas mauvais et est l’amant de Metona, la déesse de l’amour `},
  {name: `Metona`, title: `Déesse de l’amour et de la vie, Mère de la magie de Lumière`,  img: `/DungeonOfAsun/Assets/Gods/Metona.png`, desc:`Elle est l'incarnation de la bonté, de l'amour et de la famille. Elle est vénérée par presque tous les peuples d’Asun, considérée comme la déesse la plus pure et la plus à l'écoute des mortels. Elle est parfois décrite comme étant la protectrice des mariages, des unions et de la fertilité, et elle est souvent représentée avec des attributs tels que des colombes, des roses ou des cœurs. Sa présence est considérée comme réconfortante et apaisante pour ceux qui cherchent l'amour et la romance. Metona est également connue pour son humilité et sa sagesse. Elle n'est pas avide de pouvoir ou de richesse, mais plutôt de voir ses fidèles s'épanouir et trouver le bonheur. Elle est souvent représentée comme une figure maternelle, prête à écouter et à conseiller tous ceux qui se tournent vers elle avec un cœur sincère. En tant que déesse de l'amour, elle est également souvent associée à la beauté et à l'harmonie. Les artistes et les poètes la vénèrent pour son inspiration, et les amoureux cherchent souvent son aide pour trouver l'équilibre et la passion dans leur relation.En dehors de son rôle d'entremetteuse, Metone est également associée à la protection de la famille et de la communauté. Elle est souvent invoquée pour assurer la sécurité et le bien-être de ceux qui sont chers à son cœur. En fin de compte, Metona est une déesse aimante et attentionnée qui incarne les plus belles qualités de l'humanité. Elle est une figure de réconfort et de sagesse pour tous ceux qui cherchent à trouver l'amour et la paix dans un monde parfois difficile et chaotique.`},
  {name: `Riannedos`, title: `Dieu du Temps, Maître de la magie de la foudre`,  img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Rianedos, le dieu-dragon du temps, est l'un des plus anciens et des plus puissants dieux de l'univers connu. Son corps gigantesque enveloppe la planète entière, donnant à sa présence une aura intimidante et majestueuse. Sa peau est recouverte d'écailles éblouissantes, brillant sous la lumière éternelle des étoiles. En tant que gardien du temps, Rianedos possède une sagesse inégalée et une connaissance profonde de la création et de la destruction. Il peut manipuler le temps et les saisons à sa guise, faisant apparaître des tempêtes de neige ou des vagues de chaleur brûlantes selon son bon vouloir. Cependant, il est également conscient que chaque chose a une fin, même lui-même. C'est pourquoi Rianedos est souvent considéré comme un dieu mélancolique, qui observe le temps s'écouler lentement et irrémédiablement. Malgré cela, il n'hésite pas à intervenir lorsqu'il sent que l'équilibre du temps est menacé. Il peut utiliser ses pouvoirs pour réparer les failles temporelles ou pour aider les mortels à résoudre des problèmes liés au temps. Mais Rianedos est également un dieu difficile à approcher. Les mortels qui ont tenté de lui demander des faveurs ont souvent été confrontés à des épreuves difficiles ou à des conditions strictes. Il est impitoyable envers ceux qui abusent du temps ou qui cherchent à manipuler ses pouvoirs pour leur propre bénéfice. En fin de compte, la présence de Rianedos dans l'univers est un rappel constant de la nature cyclique du temps et de la nécessité de respecter les lois de l'univers. Sa puissance et sa sagesse sont à la fois fascinantes et effrayantes, et même les autres dieux le respectent en tant que gardien ultime du temps.`},
  {name: `Teomis`, title: `Dieu de l’ordre. Père de la magie de Terre`,  img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Theomis est le gardien intransigeant de l'ordre divin, son regard perçant scrutant les âmes et évaluant chaque action en fonction de sa moralité. Il est considéré comme le créateur de l'humanité, donnant forme à la première créature à partir de la poussière et de la terre. En tant que dieu de l'ordre, il est également le père de la magie de la Terre, la source de toute énergie et de toute vie sur Asun. Il est décrit comme ayant un caractère rigide et inflexible, représentant la justice incontestable et la loi inébranlable. Sa voix retentit comme un tonnerre dans les tempêtes les plus tumultueuses, et sa colère est capable d'anéantir des armées entières. Il est souvent représenté sous les traits d'un guerrier à l'armure immaculée, portant un bouclier et une épée, symbolisant la force de la loi qu'il protège. Ses fidèles sont des gardiens zélés de l'ordre et de la justice, souvent appelés à faire régner la loi dans des situations dangereuses. Les prières adressées à Theomis sont souvent des requêtes pour une guidance et une force lors de combats pour la justice et la protection des plus faibles. `},
  {name: `Quara`, title: `Déesse de La Nature, Mère de la Magie des Plantes`,  img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Quaara est la déesse de la nature, vénérée par les peuples d'Asun comme la protectrice des plantes. Elle est la mère de la magie des plantes et est considérée comme la créatrice de la flore qui peuple le plan terrestre. On dit qu'elle est à l'origine des forêts, des prairies, des champs et des jardins qui embellissent le monde. Quaara est également associée à la création des elfes, qu'elle a "améliorés" en leur inculquant le respect de la nature et de ses créations. `},
  {name: `Eone`, title: `Dieu des Savoirs et Savoir Interdit. Maître de la magie de Divination` , img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Eone, le dieu des savoirs, est considéré comme l'une des divinités les plus érudites et les plus sages d'Asun. Son palais, qui ressemble à une immense bibliothèque infinie, abrite toutes les connaissances et tous les livres de ce monde et de bien d'autres. Il passe des millénaires à étudier, à acquérir des connaissances et à améliorer son propre savoir. Eone est souvent représenté comme un être mystérieux et étrange. Il a une apparence incompréhensible, avec des membres squelettiques et des tentacules au visage, ce qui peut faire fuir les mortels qui ne sont pas prêts à affronter sa présence. Les rares fois où il s'adresse aux mortels, c'est souvent pour partager sa sagesse et sa connaissance, ou pour avertir de dangers imminents. Eone est également chargé de récupérer des savoirs et des livres sur le plan terrestre qui sont jugés trop dangereux pour être connus des hommes, afin de les protéger des ténèbres qui peuvent les corrompre. Sa quête de savoir infinie peut parfois le conduire à des endroits sombres et dangereux, mais il est toujours prêt à affronter les risques pour préserver la connaissance et la sagesse.`},
  {name: `Ehmjir`, title: `Dieu des Runes, père de la magie Ancestrale` , img: `/DungeonOfAsun/Assets/Gods/Ehmjir.png`, desc:`Également appelé le maître des forges par les Nains, il est celui qui aurait appris les runes elfiques et naines a chacun de ces peuples afin qu’ils puissent se défendre contre la cruauté des hommes de Théomis. Il ne semble pas avoir de forme physique, du moins personne de la jamais vu sur le plan terrestre.
  Le dieu des runes est souvent représenté avec un marteau ou une hache, des symboles de force et de puissance. Il est également associé à un ensemble de runes mystiques, qui sont des symboles gravés sur des pierres ou des objets.
  Les adeptes de la magie runique vénèrent le dieu des runes en gravant ses symboles sur des pierres ou des objets, en récitant des prières et en effectuant des rituels. Ils cherchent sa bénédiction pour obtenir des connaissances et des conseils sur des questions importantes, pour protéger contre les dangers et pour améliorer leur chance.`},
  {name: `Gusius`, title: `Dieu Des Animaux, père de la magie Bestial` , img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Frère de Quara et Mari de Zenelia, il incarne le côté sauvage de la nature et des animaux. Il est toujours souriant et d’une grande bonté mais il a tendance a vite s’emporter surtout envers les humains qui ne respectent pas ces enfants les animaux.
  En tant que dieu de la chasse, il est vénéré par les chasseurs qui cherchent à obtenir sa bénédiction pour réussir leurs quêtes. Il est connu pour sa capacité à guider les chasseurs dans leur quête et à leur accorder la chance et la ruse nécessaires pour abattre leur proie.
  Gusius est également considéré comme un protecteur des animaux, et est souvent représenté comme un gardien de la nature sauvage. Il est capable de communiquer avec les animaux et de comprendre leurs besoins et leurs désirs. En tant que tel, il peut offrir des conseils aux chasseurs pour les aider à respecter les cycles naturels et les populations animales.
  `},
  {name: `Noheia`, title: `Déesse des Merveilles, mère de l’alchimie` , img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Déesse des merveilles, elle voit en la création de son frère Théomis les humains la plus belle chose de ce monde. Elle déploya donc ces ailes et tentacule emplie d'œil afin de veiller sur eux et chasser ce qu’il y a de plus laid dans ce monde, les créatures des ténèbres.  Les adeptes de la déesse des merveilles cherchent son inspiration pour leur travail créatif, qu'il s'agisse de peinture, de sculpture, d'écriture ou d'invention. Ils considèrent que l'ouverture d'esprit et l'ouverture aux merveilles du monde sont essentielles pour stimuler la créativité et l'innovation. La déesse des merveilles est souvent invoquée lors de festivals artistiques et culturels, où les gens se rassemblent pour célébrer leur créativité et leur imagination. En tant que déesse des merveilles, elle est souvent associée à la liberté d'esprit et à la capacité de voir le monde avec des yeux neufs et émerveillés. Les adeptes de la déesse des merveilles cherchent à vivre leur vie avec curiosité et ouverture d'esprit, en célébrant les petites merveilles du quotidien et en cherchant constamment de nouvelles expériences.`},
  {name: `Kyhara`, title: `Déesse De L'Hiver, mère de la magie de Glace` , img: `/DungeonOfAsun/Assets/placeholder-1.png`, desc:`Elle représente le froid, la neige et la mort. Elle est souvent décrite comme une femme sévère et froide, avec des yeux d'un bleu glacé et des cheveux argentés. Elle est vénérée par les peuples qui vivent dans des régions froides et enneigées, car elle est considérée comme la gardienne de la nature en hiver. Elle est également associée à la mort et à la renaissance, car elle est responsable de la fin de l'année et du début d'une nouvelle.
  Kyhara est souvent représentée comme impitoyable, utilisant la force de la nature pour éliminer les faibles et les indésirables. Cependant, elle est également considérée comme juste et impartiale, récompensant ceux qui sont forts et persévérants dans leur quête de survie. Elle est souvent invoquée pour protéger les voyageurs qui se déplacent à travers les terres glacées et les marins qui naviguent sur des eaux dangereuses.`},
]
export const minorGods= [
  {name: `Edes`, title: `Le Justicier`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Edis`, title: `Gardien des Cieux`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Zenelia`, title: `Prêtresse de la Nature, mère de la magie druidyque`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Xegmir`, title: `Le messager, Dieu de la pénitence`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Cione`, title: `Déesse de l’aube`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Cirana`, title: `Déesse du crépuscule`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Heilong`, title: `Dieu du courage`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Hrothgar`, title: `Héros légendaire des Hightlands`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
]
export const kingGods= [
  {name: `Phiella`, title: `La tentadrice symbole de Luxure, du Sexe et l’infidelité`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Rhabus`, title: `Dieu de la Violence et de la Destruction, Jumeaux de Teomis, Maître de la Magie du Feu`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Buklos`, title: `Roi de la Débauche et des ivrognes`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Qaas`, title: `Le dormeur symbole de l'oisiveté, de la paresse et des mendiants, Père de la Magie de l’air`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Tumtum`, title: `Le fou symbole de la folie et du chaos`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Neien`, title: `Dieu de la vengeance`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
]
export const princeGods= [
  {name: `Sithis`, title: `Le bourreau, Dieu du meurtre`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Othar`, title: `Dieu des marchés`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Thorvarus`, title: `Dieu des complots`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Zadir`, title: `Dieu des sacrifices`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Archombre`, title: `Dieu du sang`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
  {name: `Belzebuth`, title: `Dieu des hommes bêtes`, img: `/DungeonOfAsun/Assets/placeholder-1.png`},
]